name: main

on:
  push:
    branches: [main]
    paths:
      - 'robot/**' 

jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    container: python:3.9
    env:
      RELEASE_BRANCH: "refs/heads/main"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt --trusted-host pypi.org --trusted-host files.pythonhosted.org
          python -m pip install -r requirements.txt --trusted-host pypi.org --trusted-host files.pythonhosted.org

      - name: Run Lint
        run: python -m flake8

      - name: Run Tests
        run: pytest
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/* --verbose
